// ALERT
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// REGISTER
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

// LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// USER
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_DELETED = 'USER_DELETED';
export const PASSWORD_UPDATED = 'PASSWORD_UPDATED';
export const NAME_UPDATED = 'NAME_UPDATED';
export const PROFILE_PICTURE_UPLOADED = 'PROFILE_PICTURE_UPLOADED';
export const PROFILE_PICTURE_REMOVED = 'PROFILE_PICTURE_REMOVED';

// LOGOUT/CLEAR PROFILE
export const LOGOUT = 'LOGOUT';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_DELETED = 'PROFILE_DELETED';

// PROFILE
export const PROFILE_LOADED = 'PROFILE_LOADED';
export const ALL_PROFILES_LOADED = 'ALL_PROFILES_LOADED';
export const PROFILE_ERROR = 'PROFILE_ERROR';

// EXPERIENCE
export const EXPERIENCE_ADDED = 'EXPERIENCE_ADDED';
export const EXPERIENCE_REMOVED = 'EXPERIENCE_REMOVED';

// EDUCATION
export const EDUCATION_ADDED = 'EDUCATION_ADDED';
export const EDUCATION_REMOVED = 'EDUCATION_REMOVED';

// POST
export const ALL_POSTS_LOADED = 'ALL_POSTS_LOADED';
export const POST_LOADED = 'POST_LOADED';
export const POST_ADDED = 'POST_ADDED';
export const POST_REMOVED = 'POST_REMOVED';
export const POST_LIKED = 'POST_LIKED';
export const POST_UNLIKED = 'POST_UNLIKED';
export const POST_ERROR = 'POST_ERROR';
export const COMMENT_ADDED_POST = 'COMMENT_ADDED_POST';
export const COMMENT_REMOVED_POST = 'COMMENT_REMOVED_POST';
export const COMMENT_ERROR_POST = 'COMMENT_ERROR_POST';

// GROUP
export const ALL_GROUPS_LOADED = 'ALL_GROUPS_LOADED';
export const ALL_GROUPS_LOADED_FOR_USER = 'ALL_GROUPS_LOADED_FOR_USER';
export const GROUP_CREATED = 'GROUP_CREATED';
export const GROUP_LOADED = 'GROUP_LOADED';
export const GROUP_UPDATED = 'GROUP_UPDATED';
export const GROUP_DELETED = 'GROUP_DELETED';
export const GROUP_REQUEST_SENT = 'GROUP_REQUEST_SENT';
export const GROUP_REQUEST_DELETED = 'GROUP_REQUEST_DELETED';
export const GROUP_MEMBER_ADDED = 'GROUP_MEMBER_ADDED';
export const GROUP_MEMBER_REMOVED = 'GROUP_MEMBER_REMOVED';
export const GROUP_ERROR = 'GROUP_ERROR';

// CAMPAIGN
export const All_CAMPAIGNS_LOADED = 'All_CAMPAIGNS_LOADED';
export const All_CAMPAIGNS_LOADED_FOR_USER = 'All_CAMPAIGNS_LOADED_FOR_USER';
export const CAMPAIGN_CREATED = 'CAMPAIGN_CREATED';
export const CAMPAIGN_LOADED = 'CAMPAIGN_LOADED';
export const CAMPAIGN_UPDATED = 'CAMPAIGN_UPDATED';
export const CAMPAIGN_DELETED = 'CAMPAIGN_DELETED';
export const CAMPAIGN_ERROR = 'CAMPAIGN_ERROR';
export const CAMPAIGN_SUPPORTED = 'CAMPAIGN_SUPPORTED';
export const COMMENT_ADDED_CAMPAIGN = 'COMMENT_ADDED_CAMPAIGN';
export const COMMENT_REMOVED_CAMPAIGN = 'COMMENT_REMOVED_CAMPAIGN';
export const COMMENT_ERROR_CAMPAIGN = 'COMMENT_ERROR_CAMPAIGN';

// TESTING
export const ALL_PROJECTS_LOADED = 'ALL_PROJECTS_LOADED';
export const ALL_PROJECTS_LOADED_FOR_USER = 'ALL_PROJECTS_LOADED_FOR_USER';
export const PROJECT_LOADED = 'PROJECT_LOADED';
export const PROJECT_OFFER_SENT = 'PROJECT_OFFER_SENT';
export const PROJECT_DELETED = 'PROJECT_DELETED';
export const PROJECT_ERROR = 'PROJECT_ERROR';
