// ALERT
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// REGISTER
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

// LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// USER
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_DELETED = 'USER_DELETED';

// LOGOUT/CLEAR PROFILE
export const LOGOUT = 'LOGOUT';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_DELETED = 'PROFILE_DELETED';

// PROFILE
export const PROFILE_LOADED = 'PROFILE_LOADED';
export const ALL_PROFILES_LOADED = 'ALL_PROFILES_LOADED';
export const PROFILE_ERROR = 'PROFILE_ERROR';

// EXPERIENCE
export const EXPERIENCE_ADDED = 'EXPERIENCE_ADDED';
export const EXPERIENCE_REMOVED = 'EXPERIENCE_REMOVED';

// EDUCATION
export const EDUCATION_ADDED = 'EDUCATION_ADDED';
export const EDUCATION_REMOVED = 'EDUCATION_REMOVED';

// POST
export const ALL_POSTS_LOADED = 'ALL_POSTS_LOADED';
export const POST_LOADED = 'POST_LOADED';
export const POST_ADDED = 'POST_ADDED';
export const POST_REMOVED = 'POST_REMOVED';
export const POST_LIKED = 'POST_LIKED';
export const POST_UNLIKED = 'POST_UNLIKED';
export const POST_ERROR = 'POST_ERROR';
export const COMMENT_ADDED = 'COMMENT_ADDED';
export const COMMENT_REMOVED = 'COMMENT_REMOVED';
export const COMMENT_ERROR = 'COMMENT_ERROR';

// CrowdFunding
export const CAMPAIGN_UPLOADED = 'CAMPAIGN_UPLOADED';
export const CLEAR_CAMPAIGN = 'CLEAR_CAMPAIGN';

// GROUP
export const ALL_GROUPS_LOADED = 'ALL_GROUPS_LOADED';
export const GROUP_ERROR = 'GROUP_ERROR';
